### ISSUE TITLE
How to disable transparency

### ISSUE THREAD

**Issue by JayBizzle** [dotcypress/hyperterm-hypermaterial#2]
Hi,

Great theme, thanks very much!

Just wondering what would be the easiest way to disable the transparency?

Thanks

**Comment by dotcypress** [comment]
Hi,

I plan to make 2 separated themes: with transparency and without.
Stay tuned 😉

**Comment by dotcypress** [comment]
Done!

Update plugins please ;)

**Comment by JayBizzle** [comment]
Brilliant, thanks!
