### ISSUE TITLE
Git colors

### ISSUE THREAD

**Issue by omarojo** [dotcypress/hyperterm-hypermaterial#4]
What are you using to have those styles for your git branches and stuff. I see the master branch in your screenshot with yellow colour. how do you do that ?

**Comment by dotcypress** [comment]
Hey, i use [Oh My Zsh](https://github.com/robbyrussell/oh-my-zsh) + [`custom zsh theme`](https://gist.github.com/dotcypress/7aa0b1717d8478fe0f305a8ce548d6f2)

**Comment by omarojo** [comment]
Cool Thankyou !! .. but it seems you are using some sort of special font ? I dont get to see the branch yellow icon.  How do you do that?

**Comment by dotcypress** [comment]
[Hack: A typeface designed for source code](https://github.com/chrissimpkins/Hack)
